package com.liuguoquan.commom.dao;

import com.liuguoquan.commom.bean.User;
import java.util.Map;
import net.sqlcipher.database.SQLiteDatabase;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

  private final DaoConfig userDaoConfig;

  private final UserDao userDao;

  public DaoSession(SQLiteDatabase db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
    super(db);

    userDaoConfig = daoConfigMap.get(UserDao.class).clone();
    userDaoConfig.initIdentityScope(type);

    userDao = new UserDao(userDaoConfig, this);

    registerDao(User.class, userDao);
  }

  public void clear() {
    userDaoConfig.clearIdentityScope();
  }

  public UserDao getUserDao() {
    return userDao;
  }
}
